const HIDDEN_LAYOUT_MODE = 'hidden';
const WIDGET_LAYOUT_MODE = 'widget';
const APP_LAYOUT_MODE = 'app';
const CONTAINER_LAYOUT_MODE = 'container';

const DEFAULT_LAYOUT_MODE = HIDDEN_LAYOUT_MODE;
const DEFAULT_PREPOSITION_MODE = 'row';

export {
    HIDDEN_LAYOUT_MODE,
    WIDGET_LAYOUT_MODE,
    APP_LAYOUT_MODE,
    CONTAINER_LAYOUT_MODE,
    DEFAULT_LAYOUT_MODE,
    DEFAULT_PREPOSITION_MODE
}